services:
    frontend:
        container_name: maple_frontend
        build: ./frontend
        ports:
            - "3001:80"
        restart: unless-stopped
        depends_on:
            - backend

    backend:
        container_name: maple_backend
        build: ./express
        ports:
            - "8080:80"
        volumes:
            - pers_data:/usr/src/web/.persistent
        restart: unless-stopped

volumes:
    pers_data:
