services:
    frontend:
        container_name: maple_frontend
        build: ./frontend
        ports:
            - "80:3000"
        restart: unless-stopped
    # backend:
    #     container_name: maple_backend
    #     build: ./backend
    #     ports:
    #         - "8000:8000"
    #     restart: unless-stopped
