services:
    frontend:
        container_name: maple_frontend
        build: 
            context: ./frontend
            args:
                VITE_API_BASE_URL: http://localhost:8080
        ports:
            - "80:80"
        restart: unless-stopped
        depends_on:
            - backend

    backend:
        container_name: maple_backend
        build: ./express
        ports:
            - "8080:80"
        volumes:
            - pers_data:/usr/src/web/.persistent
        restart: unless-stopped
        environment:
            SERVER_URL: http://localhost:8080
            SERVER_CORS_ORIGINS: >
                http://localhost,
                http://localhost:8080

volumes:
    pers_data:
