services:
  frontend:
    container_name: maple/frontend
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped
  backend:
    container_name: maple/backend
    build: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped
