services:
    frontend:
        container_name: maple_frontend
        build: ./frontend
        ports:
            - "3001:80"
        restart: unless-stopped
        depends_on:
            - backend
        environment:
            - VITE_API_BASE_URL=http://localhost:8080

    backend:
        container_name: maple_backend
        build: ./express
        ports:
            - "8080:80"
        volumes:
            - pers_data:/usr/src/web/.persistent
        restart: unless-stopped
        environment:
            SERVER_URL: https://digiapi.teschnik.de
            SERVER_CORS_ORIGINS: >
                http://localhost:3001,
                http://localhost:8080

volumes:
    pers_data:
